name: marflexV4

services:
  mysql:
    image: vruizz9/mysql:1.0.0
    container_name: mysql
    stdin_open: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: bdmarflex
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    restart: always
    networks:
      - marflexnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456789
    ports:
      - "80:80"
    restart: always
    networks:
      - marflexnet

  backend:
    image: vruizz9/backend:1.0.0
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./src/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - marflexnet

  frontend:
    image: vruizz9/frontend:1.0.0
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
    restart: always
    networks:
      - marflexnet

networks:
  marflexnet:
    driver: bridge