# Usa una imagen oficial de Node.js como base
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . ./

# Expone el puerto en el que corre tu app (ajusta si usas otro)
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["node", "server.js"]